#!/usr/bin/bash
set -e

slip=$(date +%Y%m%d%H%M%S)
dir=~/z/slips/

if [ -a /usr/bin/vimx ]; then
  /usr/bin/vimx $dir$slip
else
  /usr/bin/vi $dir$slip
fi

if [[ -f ~/z/slips/$slip ]]; then
  cd $dir
  heading=$(sed -n -e '1 s/# //p' $dir$slip)
  test -n "$heading" || (echo "Slip main head not proper." && exit 1)
  git pull -q
  echo "Slip committed: $heading"
  git add -A "$dir$slip" &>/dev/null
  git commit -m "$heading" &>/dev/null
  git push &>/dev/null
  cd - &>/dev/null
  else
    echo "Slipped the mind, nevermind."
fi
